language: generic
os:
  - linux
dist: trusty
sudo: false

# Build for all chains since Rust 1.8.0 (not available for prior versions)
env:
  - RUST=nightly
  - RUST=beta
  - RUST=stable
  - RUST=1.12.0

# Install rust
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustup toolchain install $RUST
  - rustup default $RUST
  - rustup target add arm-unknown-linux-gnueabihf
  - rustc -V
  - cargo -V
  - cp scripts/config ~/.cargo/config
  - git clone https://github.com/raspberrypi/tools.git ~/pi-tools
  - cp scripts/gcc-sysroot ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
  - chmod +x ~/pi-tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/gcc-sysroot

script:
  - ./cross64 build -v --features strict
  - ./cross64 build -v --features "orangepi strict"
  - ./cross64 build -v --example flashing_lights
  - ./cross64 build -v --features orangepi --example flashing_lights

  # development mode
  - cargo build -v --features development
  - cargo build -v --features development --example flashing_lights

  - cargo doc -v

after_success: curl https://raw.githubusercontent.com/ogeon/travis-doc-upload/master/travis-doc-upload.sh | sh
